FROM jenkins/jenkins:lts
USER root

# Install prerequisites & official Docker CLI
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    && curl -fsSL https://get.docker.com | sh

USER jenkins