version: '3.8'

services:
  # 1. SERVICE NAME (Nickname for Compose & depends_on)
  backend:
    build: ./backend
    image: todo-backend:v1.0.2     
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=todos
    depends_on:
      - mysql-db
    networks:
      - todo-network
    
  # 2. SERVICE NAME
  frontend:
    build: ./frontend
    image: todo-frontend:v1.0.2
  
    depends_on:
      - backend                 # <--- References the SERVICE NAME above!
    networks:
      - todo-network
  # 3. SERVICE NAME
  mysql-db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todos
      MYSQL_USER: todos
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - mysql-db
    networks:
      - todo-network


# Shared Bridge Network
networks:
  todo-network:
    driver: bridge

# Persistent Data Storage
volumes:
  mysql-data:
  jenkins_data: